# Generated by Django 4.2.14 on 2025-03-25 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="edit_history",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="edit_history",
        ),
        migrations.RemoveField(
            model_name="onetoonemessage",
            name="edit_history",
        ),
    ]
