# Generated by Django 4.2.14 on 2025-03-17 21:55

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "appointment_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("duration", models.DurationField(blank=True, null=True)),
            ],
            options={
                "db_table": "therapist_appointment",
            },
        ),
        migrations.CreateModel(
            name="ClientFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        help_text="Provide detailed feedback about your session"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "session_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the therapy session occurred",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-session_date", "-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TherapistProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID for external references",
                        unique=True,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="License number format: AA-123456",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="therapist_profile_pics/"
                    ),
                ),
                (
                    "treatment_approaches",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Therapy methods and approaches used",
                        null=True,
                    ),
                ),
                (
                    "available_days",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weekly availability schedule",
                        null=True,
                    ),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("video_session_link", models.URLField(blank=True, null=True)),
                (
                    "languages_spoken",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Languages the therapist can conduct sessions in",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_profile_complete", models.BooleanField(default=False)),
                (
                    "profile_completion_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "verification_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                (
                    "last_verification_attempt",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Therapist Profile",
                "verbose_name_plural": "Therapist Profiles",
                "db_table": "therapist_profile",
            },
        ),
    ]
