# Generated by Django 4.2.14 on 2025-03-17 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0002_initial"),
        ("therapist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_note",
                to="therapist.appointment",
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="therapist.appointment",
            ),
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_feedback_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_feedback_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to="patient.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_appointments",
                to="therapist.therapistprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(fields=["user"], name="therapist_p_user_id_7c1d59_idx"),
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(
                fields=["specialization"], name="therapist_p_special_75a3e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(
                fields=["is_verified"], name="therapist_p_is_veri_d2d62b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["-session_date"], name="therapist_s_session_22a96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["therapist", "patient"], name="therapist_s_therapi_cac6e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientfeedback",
            index=models.Index(
                fields=["-timestamp"], name="therapist_c_timesta_20cee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientfeedback",
            index=models.Index(
                fields=["therapist", "rating"], name="therapist_c_therapi_ba58ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientfeedback",
            constraint=models.UniqueConstraint(
                fields=("patient", "therapist", "appointment"),
                name="unique_appointment_feedback",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["therapist", "appointment_date"],
                name="therapist_a_therapi_9bd01c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="therapist_a_patient_4f9bd9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                check=models.Q(("appointment_date__gt", models.F("created_at"))),
                name="appointment_future_date_check",
            ),
        ),
    ]
