# Generated by Django 4.2.14 on 2025-03-17 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moodlog",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mood_logs",
                to="patient.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="medicalhistoryentry",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_history_entries",
                to="patient.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="healthmetric",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_metrics",
                to="patient.patientprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="moodlog",
            index=models.Index(
                fields=["patient", "logged_at"], name="patient_moo_patient_69f7ec_idx"
            ),
        ),
    ]
