# Generated by Django 4.2.14 on 2025-03-25 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MoodLog",
        ),
    ]
