# Generated by Django 4.2.14 on 2025-03-25 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="last_mood_checkin",
        ),
    ]
